package com.test.tutorial5_1tablerelations.data

import android.arch.persistence.room.Entity
import android.arch.persistence.room.ForeignKey
import android.arch.persistence.room.ForeignKey.CASCADE
import android.arch.persistence.room.Index
import android.arch.persistence.room.PrimaryKey

/**
 * Data class that contains [Pet] data.
 * [User.id] is in [User] class, [userId] is in [Pet] class both points the same value. [Pet.petId] is auto generated by insetion to table.
 *
 * Index let this table to be sorted by userId which makes all rows with same userId to be found faster.
 */

@Entity(tableName = "pets",
        indices = arrayOf(Index(value = ["userId"])),
        foreignKeys = [ForeignKey(entity = User::class, parentColumns = ["id"], childColumns = ["userId"], onDelete = CASCADE)])
class Pet {
    @PrimaryKey(autoGenerate = true)
    var petId: Long = 0     // Pet petId
    var userId: Long = 0 // User id
    var name: String? = null
}
